title: Pixelflow Canvas
description: A virtual CRT for old school graphics programming in Visual Studio Code.
theme: just-the-docs

url: https://github.com/specht/pixelflow_canvas_vscode

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
