title: Pixelflow Canvas
description: A virtual CRT for old school graphics programming in Visual Studio Code.
theme: just-the-docs

url: https://github.com/specht/pixelflow_canvas_vscode

aux_links:
  Github: https://github.com/specht/pixelflow_canvas_vscode
callouts:
  info:
    color: yellow